config/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('reminder.urls')),
] + debug_toolbar_urls()

reminder/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.HomePage.as_view(), name='homepage'),
    path('all_reminders/', views.AllReminders.as_view(), name='all_reminders'),
    path('add_reminder/', views.AddReminder.as_view(), name='add_reminder'),
    path('update/<int:pk>/', views.UpdateReminder.as_view(), name='update_reminder'),
    path('delete/<int:pk>/', views.DeleteReminder.as_view(), name='delete_reminder'),
    path('send_test_sms_for_madval/', views.send_test_sms_for_madval),
    path('send_test_email_for_madval/', views.send_test_email_for_madval),
    path('send_test_telegram_message_for_madval/', views.send_test_telegram_message_for_madval),
]

reminder/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Reminder(models.Model):
    EVERY_YEAR          = 'every year'
    EVERY_MONTH         = 'every month'
    EVERY_28_DAY        = 'every 28 day'
    EVERY_OTHER_WEEK    = 'every other week'
    EVERY_WEEK          = 'every week'
    EVERY_THIRD_DAY     = 'every third day'
    EVERY_OTHER_DAY     = 'every other day'
    EVERY_DAY           = 'every day'
    EVERY_12_HOUR       = 'every 12 hour'
    EVERY_8_HOUR        = 'every 8 hour'
    EVERY_6_HOUR        = 'every 6 hour'
    EVERY_4_HOUR        = 'every 4 hour'

    PERIOD_CHOICES = (
        (EVERY_YEAR, 'هر سال'),
        (EVERY_MONTH, 'هر ماه'),
        (EVERY_28_DAY, 'هر ۲۸ روز'),
        (EVERY_OTHER_WEEK, 'هر دو هفته'),
        (EVERY_WEEK, 'هر هفته'),
        (EVERY_THIRD_DAY, 'هر ۷۲ ساعت'),
        (EVERY_OTHER_DAY, 'هر ۴۸ ساعت'),
        (EVERY_DAY, 'هر روز'),
        (EVERY_12_HOUR, 'هر ۱۲ ساعت'),
        (EVERY_8_HOUR, 'هر ۸ ساعت'),
        (EVERY_6_HOUR, 'هر ۶ ساعت'),
        (EVERY_4_HOUR, 'هر ۴ ساعت'),
    )
    user = models.ForeignKey(to=get_user_model(), on_delete=models.CASCADE, related_name='reminders')
    title = models.CharField(max_length=64)
    start_datetime = models.DateTimeField()
    period = models.CharField(max_length=64, choices=PERIOD_CHOICES)
    active = models.BooleanField(default=True, verbose_name='فعال')
    sms = models.BooleanField(default=True, verbose_name='اس ام اس')
    email = models.BooleanField(default=False, verbose_name='ایمیل')
    notification = models.BooleanField(default=False, verbose_name='نوتیفیکیشن')
    telegram = models.BooleanField(default=False, verbose_name='تلگرام')
    whatsapp = models.BooleanField(default=False, verbose_name='واتساپ')
    eta = models.BooleanField(default=False, verbose_name='ایتا')
    bale = models.BooleanField(default=False, verbose_name='بله')

    def __str__(self):
        return self.title

reminder/forms.py
from django import forms

from .models import Reminder

class ReminderFormToSHow(forms.Form):
    active = forms.BooleanField(disabled=True)
    sms = forms.BooleanField(disabled=True)
    email = forms.BooleanField(disabled=True)
    telegram = forms.BooleanField(disabled=True)
    whatsapp = forms.BooleanField(disabled=True)
    notification = forms.BooleanField(disabled=True)
    eta = forms.BooleanField(disabled=True)
    bale = forms.BooleanField(disabled=True)


class ReminderForm(forms.ModelForm):
    class Meta:
        model = Reminder
        fields = ['title', 'period', 'active', 'sms', 'email', 'telegram']

    title = forms.CharField(max_length=64, label='عنوان یادآوری')
    # start_datetime = forms.DateTimeField(label='', widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))
    period = forms.TypedChoiceField(choices=Reminder.PERIOD_CHOICES, label='دوره چرخش یادآوری', widget=forms.Select(attrs={'style': 'height: 40px;'}))
    active = forms.BooleanField(required=False, initial=True, help_text='در صورت غیر فعال کردن یک یادآوری، پیامی از طرف سایت sbedeh.ir برای شما ارسال نخواهد شد.', label='فعال بودن این یادآوری')
    sms = forms.BooleanField(required=False, initial=True, help_text='جهت دریافت اس ام اس، دقت کنید که شماره های تبلیغاتی را مسدود نکرده باشید. در غیر این صورت اس ام اس های ارسالی به شما مسدود خواهند شد.', label='ارسال اس ام اس')
    email = forms.BooleanField(required=False, initial=True, help_text='جهت دریافت پیام از طریق ایمیل، باید از قسمت تنظیمات سایت آدرس ایمیل معتبر خود را وارد کنید.', label='ارسال ایمیل')
    telegram = forms.BooleanField(required=False, initial=True, help_text='جهت دریافت پیغام از طریق تلگرام، باید از قسمت تنظیمات سایت، chat_id تلگرامی خود را اضافه کنید و یک پیغام از اکانت مورد نظر برای ربات تلگرامی با آی دی @sbedeh_bot ارسال کنید تا ربات تلگرامی توانایی ارسال پیغام برای شما را داشته باشد.', label='ارسال پیام در تلگرام')
    # whatsapp = forms.BooleanField(disabled=True, help_text='در حال حاضر فعال نیست', label='واتساپ')
    # notification = forms.BooleanField(disabled=True, help_text='در حال حاضر فعال نیست', label='نوتیفیکیشن')
    # eta = forms.BooleanField(disabled=True, help_text='در حال حاضر فعال نیست', label='ایتا')
    # bale = forms.BooleanField(disabled=True, help_text='در حال حاضر فعال نیست', label='بله')

reminder/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from datetime import datetime
import jdatetime

from . import backend # برای این که کارها انجام بشن ایمپورت کردم. استفاده ای ازش نمیکنیم اینجا.
from .models import Reminder
from .forms import ReminderForm, ReminderFormToSHow



class HomePage(generic.TemplateView):
    template_name = 'enter_number.html'


class AllReminders(LoginRequiredMixin, generic.TemplateView):
    def get(self, request, *args, **kwargs):
        user = self.request.user
        reminders = Reminder.objects.filter(user=user).order_by('-id')
        for reminder in reminders:
            reminder.form=ReminderFormToSHow(initial={
                'active' :reminder.active,
                'sms' :reminder.sms,
                'email' :reminder.email,
                'telegram' :reminder.telegram,
                'whatsapp' :reminder.whatsapp,
                'notification' :reminder.notification,
                'eta' :reminder.eta,
                'bale' :reminder.bale,
            })
        context = {
            'reminders': reminders,
        }
        return render(request, 'all_reminders.html', context)

    def post(self, request, *args, **kwargs):
        return render(request, 'all_reminders.html')


class AddReminder(LoginRequiredMixin, generic.TemplateView):
    def get(self, request, *args, **kwargs):
        form = ReminderForm()
        context = {
            'form': form
            }
        return render(request, 'add_reminder.html', context)

    def post(self, request, *args, **kwargs):
        form = ReminderForm(request.POST)
        if form.is_valid():
            user = self.request.user
            title = request.POST.get('title')
            period = request.POST.get('period')
            active = True if request.POST.get('active') else False
            sms = True if request.POST.get('sms') else False
            email = True if request.POST.get('email') else False
            telegram = True if request.POST.get('telegram') else False
            date:str = request.POST.get('date')
            try:
                year, month, day = date.split('-')
            except:
                messages.error(request, 'تاریخ را به درستی وارد نکرده اید.')
                return render(request, 'add_reminder.html', {'form':form})
            time:str = request.POST.get('time')
            try:
                if ':' not in time:
                    hour = time
                    minute=0
                else:
                    hour, minute = time.split(':')
            except:
                messages.error(request, 'ساعت را به درستی وارد نکرده اید.')
                return render(request, 'add_reminder.html', {'form':form})
            try:
                jdt = jdatetime.datetime(int(year), int(month), int(day), int(hour), int(minute))
                dt = jdt.togregorian()
            except:
                messages.error(request, 'زمان شروع یادآوری را به درستی مشخص نکرده اید. به ساختار نوشته شده در باکس ها دقت کنید.')
                return render(request, 'add_reminder.html', {'form':form})
            Reminder.objects.create(user=user, title=title, period=period, active=active, sms=sms, email=email, telegram=telegram, start_datetime=dt)
        else:
            messages.error(request, form.errors)
            return render(request, 'add_reminder.html', {'form':form})
        return redirect('all_reminders')


class UpdateReminder(LoginRequiredMixin, generic.UpdateView):
    model = Reminder

    def get(self, request, *args, **kwargs):
        obj:Reminder = self.get_object()
        form = ReminderForm(instance=obj)
        context = {
            'reminder': obj,
            'form': form,
            }
        return render(request, 'update_reminder.html', context)

    def post(self, request, *args, **kwargs):
        obj:Reminder = self.get_object()
        form = ReminderForm(request.POST, instance=obj)
        context = {
            'reminder': obj,
            'form': form,
            }
        if form.is_valid():
            title = request.POST.get('title')
            period = request.POST.get('period')
            active = True if request.POST.get('active') else False
            sms = True if request.POST.get('sms') else False
            email = True if request.POST.get('email') else False
            telegram = True if request.POST.get('telegram') else False
            date:str = request.POST.get('date')
            try:
                year, month, day = date.split('-')
            except:
                messages.error(request, 'تاریخ را به درستی وارد نکرده اید.')
                return render(request, 'update_reminder.html', context)
            time:str = request.POST.get('time')
            try:
                if ':' not in time:
                    hour = time
                    minute=0
                else:
                    hour, minute = time.split(':')
            except:
                messages.error(request, 'ساعت را به درستی وارد نکرده اید.')
                return render(request, 'update_reminder.html', context)
            try:
                jdt = jdatetime.datetime(int(year), int(month), int(day), int(hour), int(minute))
                dt = jdt.togregorian()
            except:
                messages.error(request, 'زمان شروع یادآوری را به درستی مشخص نکرده اید. به ساختار نوشته شده در باکس ها دقت کنید.')
                return render(request, 'update_reminder.html', context)
            obj.title = title
            obj.period = period
            obj.active = active
            obj.sms = sms
            obj.email = email
            obj.telegram = telegram
            obj.start_datetime = dt
            obj.save()
        else:
            messages.error(request, form.errors)
            return render(request, 'update_reminder.html', context)
        return redirect('all_reminders')


class DeleteReminder(LoginRequiredMixin, generic.DeleteView):
    model = Reminder
    template_name = 'delete_reminder.html'

    def post(self, request, *args, **kwargs):
        reminder = self.get_object()
        reminder.delete()
        messages.success(self.request, 'یادآور %s با موفقیت حذف شد.' %reminder.title)
        return redirect('all_reminders')


def send_test_sms_for_madval(request):
    backend.send_s()
    return render(request, 'enter_number.html')


def send_test_email_for_madval(request):
    backend.send_e()
    return render(request, 'enter_number.html')


def send_test_telegram_message_for_madval(request):
    backend.send_t()
    return render(request, 'enter_number.html')

reminder/templates/add_reminder.html
{% extends "_base.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block page_title %}
افزودن یادآوری
{% endblock page_title %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'admin/css/dark_mode.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/nav_sidebar.css' %}">
<script src="{% static 'admin/js/nav_sidebar.js' %}" defer></script>
<link rel="stylesheet" href="{% static 'admin/css/forms.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/rtl.css' %}">
<link href="{% static 'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css' %}" media="all" rel="stylesheet">
<script src="{% static 'admin/js/django_jalali.min.js' %}"></script>
{% endblock extra_css %}


{% block content %}
<div class='container-lg my-5 p-5 c'>
    <form action="" method="post">
        {% csrf_token %}
        <label class="required mx-2">تاریخ شروع یادآوری*</label>
            تاریخ:
                <input type="text" name="date" class="jalali_date-date mx-1" size="10" required id="date" placeholder="1403-06-06">
            زمان:
                <input type="text" name="time" class="vTimeField mx-1" size="8" required id="time" placeholder="مثلا 18:30">
        {{ form|crispy }}
        <button class="btn btn-success px-3" type="submit">افزودن</button>
    </form>
</div>
{% endblock content %}


{% block active_add_reminder %}active{% endblock active_add_reminder %}

reminder/templates/all_reminders.html
{% extends "_base.html" %}

{% load jalali_tags %}
{% load madval_persian_translation %}

{% block page_title %}
تمام یادآوری ها
{% endblock page_title %}


{% block content %}
<div class="container-lg scrollmenu mb-5">
    <table class="table table-lg table-hover table-dark mt-3">
        <tr>
            <th rowspan="2" style="width: 25%">عنوان</th>
            <th rowspan="2" style="width: 25%">تاریخ و زمان شروع</th>
            <th rowspan="2" style="width: 15%">دوره یادآوری</th>
            <th rowspan="2" style="width: 5%">فعال</th>
            <th colspan="7" style="width: 20%">ارسال پیغام از طریق</th>
            <th rowspan="2" style="width: 5%">ویرایش</th>
            <th rowspan="2" style="width: 5%">حذف</th>
        </tr>
        <tr>
            <th style="width: 3%">sms</th>
            <th style="width: 3%">email</th>
            <th style="width: 3%">telegram</th>
            <th style="width: 3%">whatsapp</th>
            <th style="width: 3%">notification</th>
            <th style="width: 3%">eta</th>
            <th style="width: 3%">bale</th>
        </tr>
        {% for reminder in reminders %}
        <tr class="table-info">
            <td><a href="{% url 'update_reminder' reminder.pk %}" class="text-decoration-none text-dark">{{ reminder.title }}</a></td>
            <td><a href="{% url 'update_reminder' reminder.pk %}" class="text-decoration-none text-dark">{{ reminder.start_datetime|to_jalali:'%Y/%m/%d ساعت %H:%M'|pn }}</a></td>
            <td><a href="{% url 'update_reminder' reminder.pk %}" class="text-decoration-none text-dark">{{ reminder.get_period_display }}</a></td>
            <td>{{ reminder.form.active }}</td>
            <td>{{ reminder.form.sms }}</td>
            <td>{{ reminder.form.email }}</td>
            <td>{{ reminder.form.telegram }}</td>
            <td>{{ reminder.form.whatsapp }}</td>
            <td>{{ reminder.form.notification }}</td>
            <td>{{ reminder.form.eta }}</td>
            <td>{{ reminder.form.bale }}</td>
            <td><a href="{% url 'update_reminder' reminder.pk %}" class="btn btn-sm btn-warning">ویرایش</a></td>
            <td><a href="{% url 'delete_reminder' reminder.pk %}" class="btn btn-sm btn-danger">حذف</a></td>
        </tr>
        {% endfor %}
    </table>
</div>
<br>
<br>
{% endblock content %}


{% block active_all_reminders %}active{% endblock active_all_reminders %}

reminder/templates/delete_reminder.html
{% extends "_base.html" %}

{% block page_title %}
حذف یادآوری
{% endblock page_title %}

{% block content %}
<div class='container-lg my-5 p-5 c'>
    <h1>
        از حذف یادآوری
        <span class="text-info">"{{ reminder.title }}"</span>
        مطمئنید؟ می توانید از قسمت
        <a class="text-decoration-none" href="{% url 'update_reminder' reminder.pk %}">ویرایش</a>،
        وضعیت آن را به غیر فعال تغییر دهید تا برای شما یادآوری ارسال نشود و در صورت نیاز
        دوباره آن را فعال کنید.
    </h1>
    <a class="btn btn-warning mx-2" href="{% url 'update_reminder' reminder.pk %}">ویرایش {{ reminder.title }}</a>
    <a class="btn btn-secondary mx-2" onclick="window.history.back()">بازگشت به صفحه قبل</a>
    <form class="d-inline-block mx-2 mt-4" action="" method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="مطمئنم. حذف شود">
    </form>
</div>
{% endblock content %}

reminder/templates/index.html
{% extends "_base.html" %}

{% block page_title %}
خانه
{% endblock page_title %}

{% block content %}
سلام
{% endblock content %}

reminder/templates/update_reminder.html
{% extends "_base.html" %}

{% load static %}

{% load jalali_tags %}
{% load crispy_forms_tags %}

{% block page_title %}
ویرایش یادآوری {{ reminder.title }}
{% endblock page_title %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'admin/css/dark_mode.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/nav_sidebar.css' %}">
<script src="{% static 'admin/js/nav_sidebar.js' %}" defer></script>
<link rel="stylesheet" href="{% static 'admin/css/forms.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/rtl.css' %}">
<link href="{% static 'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css' %}" media="all" rel="stylesheet">
<script src="{% static 'admin/js/django_jalali.min.js' %}"></script>
{% endblock extra_css %}


{% block content %}
<div class='container-lg my-5 p-5 c'>
    <form action="" method="post">
        {% csrf_token %}
        <label class="required mx-2">تاریخ شروع یادآوری*</label>
            تاریخ:
                <input type="text" name="date" class="jalali_date-date mx-1" size="10" required id="date" placeholder="1403-06-06" value="{{ reminder.start_datetime.date|to_jalali:'%Y-%m-%d' }}">
            زمان:
                <input type="text" name="time" class="vTimeField mx-1" size="8" required id="time" placeholder="مثلا 18:30" value="{{ reminder.start_datetime.time }}">
        {{ form|crispy }}
        <button class="btn btn-warning px-3" type="submit">یادآوری {{ reminder.title }} را ویرایش کن</button>
        <a class="btn btn-secondary mx-2" onclick="window.history.back()">بازگشت به صفحه قبل</a>
    </form>
</div>
{% endblock content %}